"""Generate the condensed schema context injected into the agent's system prompt.

Reads model/model.yaml and writes model/schema_context.md. The YAML is the
declaration of record and carries evidence, provenance and commentary the agent
does not need; this renders the subset it does -- grain, columns, joins, the
patterns it must follow and the questions it must refuse.

The output is a cached generated file. `--check` re-renders and compares without
writing, so CI or a test can prove the cache is current.

Usage:
  python scripts/build_schema_context.py            # write model/schema_context.md
  python scripts/build_schema_context.py --check    # fail if the cache is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
MODEL_PATH = ROOT / "model" / "model.yaml"
OUT_PATH = ROOT / "model" / "schema_context.md"

GENERATED_BY = "scripts/build_schema_context.py from model/model.yaml -- do not edit by hand"


def flow(text: str | None) -> str:
    """Collapse a folded YAML block to one line."""
    return " ".join(str(text).split()) if text else ""


def render(model: dict) -> str:
    m, out = model["model"], []
    w = out.append

    w(f"<!-- generated by {GENERATED_BY} -->")
    w(f"# Job costing data model — `{m['lakehouse']}`, schema `{m['schema']}`")
    w("")
    w(f"{len(model['tables'])} tables queried through DuckDB. Relation names below are the exact "
      "names to use in SQL.")
    w("")
    w(f"Ignore these columns entirely — they are ingest metadata with no business meaning: "
      f"{', '.join('`' + c + '`' for c in model['lineage_columns'])}.")
    w("")

    dialect = model.get("sql_dialect")
    if dialect:
        w(f"## Writing SQL ({dialect['engine']})")
        w("")
        w(f"**{flow(dialect['relation_naming'])}**")
        w("")
        w(f"```sql\n-- correct\n{dialect['relation_example_good']}\n\n"
          f"-- fails: Catalog Error\n{dialect['relation_example_bad']}\n```")
        w("")
        w(f"**Money columns** ({', '.join('`' + c + '`' for c in dialect['money_columns'])}): "
          f"{flow(dialect['money_rule'])}")
        w("")
        w(f"```sql\n-- correct\n{dialect['money_example_good']}\n\n"
          f"-- prints 7684852.81000002\n{dialect['money_example_bad']}\n```")
        w("")

    w("## Tables")
    for t in model["tables"]:
        key = t["key"]
        w("")
        w(f"### `{t['name']}` — {t['role']}, {t['rows']:,} rows")
        w(f"**Grain:** {t['grain']}.")
        if key["unique"]:
            w(f"**Key:** `{' + '.join(key['columns'])}` (verified unique).")
        else:
            w(f"**Key:** `{' + '.join(key['columns'])}` is the intended key but is "
              f"**NOT unique in the data**. Unique combination: "
              f"`{' + '.join(key['working_key'])}`.")
        if "coverage" in t:
            w(f"**Coverage:** {t['coverage']}.")
        w("")
        w("| Column | Type | Notes |")
        w("|---|---|---|")
        for col, spec in t["columns"].items():
            w(f"| `{col}` | {spec['type']} | {flow(spec['desc'])} |")
        for note in t.get("notes", []):
            w("")
            w(f"> {flow(note)}")

    w("")
    w("## Joins")
    w("")
    w("Every relationship is many-to-one. Use the join clause exactly as given — where a "
      "cast is shown it is required, and omitting it errors or returns nothing.")

    plain = [r for r in model["relationships"] if "role" not in r]
    roles = [r for r in model["relationships"] if "role" in r]

    for rel in plain:
        f, t = rel["from"], rel["to"]
        w("")
        w(f"**`{f['table']}` → `{t['table']}`**")
        w(f"```sql\n{rel['join']}\n```")
        bullets = []
        if rel.get("optional"):
            ev = rel["evidence"]
            bullets.append(f"Optional: {ev['fact_rows_null_key']:,} of "
                           f"{ev['fact_rows_null_key'] + ev['fact_rows_with_key']:,} rows have no key. "
                           "Use LEFT JOIN.")
        if rel["evidence"].get("orphan_fact_rows"):
            bullets.append(f"{rel['evidence']['orphan_fact_rows']:,} rows have a key with no "
                           "matching dimension row — an inner join drops them.")
        if rel["evidence"].get("unreferenced_dimension_rows"):
            bullets.append(f"{rel['evidence']['unreferenced_dimension_rows']:,} dimension rows are "
                           "never referenced — start from the dimension and LEFT JOIN to keep them.")
        if rel.get("warning"):
            bullets.append(flow(rel["warning"]))
        for b in bullets:
            w(f"- {b}")

    if roles:
        w("")
        w("### `dim_date` is a role-playing dimension")
        w("")
        w("It attaches to several different date columns. Each role is a separate join needing "
          "its own **aliased** copy of `dim_date` — joining it once cannot serve two roles.")
        w("")
        w("| Role | Alias | Join | Means |")
        w("|---|---|---|---|")
        for rel in roles:
            w(f"| `{rel['role']}` | `{rel['alias']}` | `{rel['join']}` | {flow(rel['means'])} |")
        for rel in roles:
            if rel.get("warning"):
                w("")
                w(f"> **`{rel['role']}`** — {flow(rel['warning'])}")

    w("")
    w("## Required query patterns")
    for pat in model.get("analysis_patterns", []):
        w("")
        w(f"### {pat['name']}")
        w(f"Applies to: {', '.join(pat['question_shapes'])}.")
        w("")
        w(f"**{flow(pat['rule'])}**")
        w("")
        w(f"```sql\n{pat['sql'].rstrip()}\n```")
        if pat.get("grain_note"):
            w(f"- {flow(pat['grain_note'])}")
        for note in pat.get("notes", []):
            w(f"- {flow(note)}")

    w("")
    w("## Questions this data cannot answer")
    for ca in model.get("cannot_answer", []):
        w("")
        w(f"### {', '.join(ca['question_shapes'])}")
        w("")
        w(f"**Refuse, and say why.** {flow(ca['why_not'])}")
        w("")
        w(f"**What would be needed:** {flow(ca['what_would_be_needed'])}")
        w("")
        w(f"**Offer instead, as a separate question:** {flow(ca['offer_instead'])}")
        w("")
        w(f"**Do not:** {flow(ca['must_not'])}")

    w("")
    w("## Known data quality issues")
    w("")
    w("These are real defects in the source, not reasons to avoid the data. Where one affects "
      "an answer, say so in the answer.")
    w("")
    w("| # | Severity | Table | Issue | Effect on answers |")
    w("|---|---|---|---|---|")
    for dq in model["data_quality"]:
        w(f"| {dq['id']} | {dq['severity']} | `{dq['table']}` | {flow(dq['finding'])} | "
          f"{flow(dq['impact'])} |")

    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the cached file is current; write nothing")
    args = parser.parse_args()

    rendered = render(yaml.safe_load(MODEL_PATH.read_text()))

    if args.check:
        if not OUT_PATH.exists():
            print(f"{OUT_PATH} does not exist. Run: python scripts/build_schema_context.py",
                  file=sys.stderr)
            return 1
        if OUT_PATH.read_text() != rendered:
            print(f"{OUT_PATH.name} is STALE -- model.yaml has changed since it was generated.\n"
                  "Run: python scripts/build_schema_context.py", file=sys.stderr)
            return 1
        print(f"{OUT_PATH.name} is current ({len(rendered):,} chars, "
              f"~{len(rendered) // 4:,} tokens).")
        return 0

    OUT_PATH.write_text(rendered)
    print(f"wrote {OUT_PATH.relative_to(ROOT)}  ({len(rendered):,} chars, "
          f"~{len(rendered) // 4:,} tokens)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
